package main

import (
	"strings"
	"testing"
)

const sampleEN = `{
  "$schema": "https://inlang.com/schema/inlang-message-format",
  "feed_empty_title": "No loot yet.",
  "header_xp": "{xp} XP",
  "chest_row_drops": [
    {
      "declarations": ["input count", "local countPlural = count: plural"],
      "selectors": ["countPlural"],
      "match": {
        "countPlural=one": "{count} drop",
        "countPlural=other": "{count} drops"
      }
    }
  ]
}`

func TestParseMessages(t *testing.T) {
	c, err := ParseMessages([]byte(sampleEN))
	if err != nil {
		t.Fatal(err)
	}
	if len(c) != 3 {
		t.Fatalf("got %d keys, want 3 ($schema must not be one of them)", len(c))
	}
	if got := c["feed_empty_title"].Text; got != "No loot yet." {
		t.Errorf("feed_empty_title = %q", got)
	}
	v := c["chest_row_drops"]
	if !v.IsVariant() {
		t.Fatal("chest_row_drops should be a variant message")
	}
	if len(v.Variant.Match) != 2 {
		t.Errorf("got %d arms, want 2", len(v.Variant.Match))
	}
	if got := v.Variant.Selectors; len(got) != 1 || got[0] != "countPlural" {
		t.Errorf("selectors = %v", got)
	}
}

func TestParseMessagesRejectsNestedObjects(t *testing.T) {
	_, err := ParseMessages([]byte(`{"nav": {"home": "Home"}}`))
	if err == nil {
		t.Fatal("a nested object should be rejected: this catalog is flat")
	}
}

func TestMarshalMessagesIsDeterministic(t *testing.T) {
	c, err := ParseMessages([]byte(sampleEN))
	if err != nil {
		t.Fatal(err)
	}
	first, err := MarshalMessages(c)
	if err != nil {
		t.Fatal(err)
	}
	for i := 0; i < 20; i++ {
		again, err := MarshalMessages(c)
		if err != nil {
			t.Fatal(err)
		}
		if string(again) != string(first) {
			t.Fatalf("run %d differs from the first:\n%s\n---\n%s", i, first, again)
		}
	}
	out := string(first)
	if !strings.HasPrefix(out, "{\n  \"$schema\"") {
		t.Errorf("$schema should sort first and the indent should be two spaces, got:\n%s", out)
	}
	if !strings.HasSuffix(out, "}\n") {
		t.Error("the file should end with exactly one newline")
	}
	// Round-trips.
	back, err := ParseMessages(first)
	if err != nil {
		t.Fatal(err)
	}
	if back["chest_row_drops"].Hash() != c["chest_row_drops"].Hash() {
		t.Error("a variant message did not survive a round trip")
	}
}

func TestMarshalMessagesDoesNotEscapeHTMLOrUnicode(t *testing.T) {
	c := Catalog{"k": {Text: "Cupertino & Co · 3 → 4"}}
	out, err := MarshalMessages(c)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(out), "Cupertino & Co · 3 → 4") {
		t.Errorf("punctuation was escaped:\n%s", out)
	}
}

const sampleRules = `
rules:
  - name: revenuecat-churn
    match: {source: revenuecat}
    then:
      rarity: cursed
      title: "Subscriber lost"
      subtitle: "{{.Kind}}{{if .App}} · {{.App}}{{end}}"
      xp: 5
  - name: no-subtitle
    then:
      title: "Just a headline"
fallback:
  rarity: common
  title: "{{.Source}} · {{.Kind}}"
  subtitle: "{{.App}}"
`

func TestParseRules(t *testing.T) {
	c, order, err := ParseRules([]byte(sampleRules))
	if err != nil {
		t.Fatal(err)
	}
	want := []string{
		"rules/revenuecat-churn/title",
		"rules/revenuecat-churn/subtitle",
		"rules/no-subtitle/title",
		"fallback/title",
		"fallback/subtitle",
	}
	for _, k := range want {
		if _, ok := c[k]; !ok {
			t.Errorf("missing key %q", k)
		}
	}
	if len(c) != len(want) {
		t.Errorf("got %d keys, want %d: %v", len(c), len(want), c.Keys())
	}
	if _, ok := c["rules/no-subtitle/subtitle"]; ok {
		t.Error("an empty field is not a translatable unit")
	}
	if len(order) != 2 || order[0] != "revenuecat-churn" {
		t.Errorf("order = %v, want default.yaml's own order", order)
	}
}

func TestParseRulesAcceptsBothFallbackShapes(t *testing.T) {
	nested := "fallback:\n  then:\n    title: \"T\"\n    subtitle: \"S\"\n"
	c, _, err := ParseRules([]byte(nested))
	if err != nil {
		t.Fatal(err)
	}
	if c["fallback/title"].Text != "T" || c["fallback/subtitle"].Text != "S" {
		t.Errorf("a `then:`-nested fallback did not parse: %v", c)
	}
}

func TestMarshalOverlayIsDeterministicAndRoundTrips(t *testing.T) {
	c, order, err := ParseRules([]byte(sampleRules))
	if err != nil {
		t.Fatal(err)
	}
	first, err := MarshalOverlay("German", c, order)
	if err != nil {
		t.Fatal(err)
	}
	for i := 0; i < 20; i++ {
		again, err := MarshalOverlay("German", c, order)
		if err != nil {
			t.Fatal(err)
		}
		if string(again) != string(first) {
			t.Fatalf("run %d differs:\n%s\n---\n%s", i, first, again)
		}
	}
	out := string(first)
	if !strings.HasPrefix(out, "# Loot default rules — German.") {
		t.Errorf("missing the generated-file header:\n%s", out)
	}
	if !strings.Contains(out, "GENERATED by tools/translate") {
		t.Error("the header should say the file is generated")
	}
	if !strings.Contains(out, "English title or subtitle it translates changes") {
		t.Error("the header should say a hand edit survives")
	}
	// Rules keep default.yaml's order rather than being sorted, so the file
	// reads next to the source it translates.
	if strings.Index(out, "revenuecat-churn") > strings.Index(out, "no-subtitle") {
		t.Error("rules should be written in default.yaml's order")
	}

	back, _, err := ParseRules(first)
	if err != nil {
		t.Fatalf("the overlay we wrote does not parse: %v\n%s", err, out)
	}
	for _, k := range c.Keys() {
		if back[k].Text != c[k].Text {
			t.Errorf("%s: wrote %q, read back %q", k, c[k].Text, back[k].Text)
		}
	}
}

func TestMarshalOverlayQuotesTemplatesReadably(t *testing.T) {
	c := Catalog{
		"rules/x/title":    {Text: `{{if ne (printf "%v" .N) "1"}}s{{end}}`},
		"rules/x/subtitle": {Text: "{{.App}}"},
	}
	out, err := MarshalOverlay("German", c, RuleOrder{"x"})
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(out), `'{{if ne (printf "%v" .N) "1"}}s{{end}}'`) {
		t.Errorf("a template with double quotes should be single-quoted:\n%s", out)
	}
	if !strings.Contains(string(out), `subtitle: "{{.App}}"`) {
		t.Errorf("a template without quotes should be double-quoted:\n%s", out)
	}
}

func TestHashIsStableAndSensitive(t *testing.T) {
	a := Value{Text: "New subscriber"}
	if a.Hash() != (Value{Text: "New subscriber"}).Hash() {
		t.Error("the same string should hash the same")
	}
	if a.Hash() == (Value{Text: "New subscribers"}).Hash() {
		t.Error("a changed string must hash differently")
	}

	v1 := Value{Variant: &Variant{
		Declarations: []string{"input count"},
		Selectors:    []string{"countPlural"},
		Match:        map[string]string{"countPlural=one": "a", "countPlural=other": "b"},
	}}
	v2 := Value{Variant: &Variant{
		Declarations: []string{"input count"},
		Selectors:    []string{"countPlural"},
		Match:        map[string]string{"countPlural=other": "b", "countPlural=one": "a"},
	}}
	if v1.Hash() != v2.Hash() {
		t.Error("map iteration order must not affect the hash")
	}
	v2.Variant.Match["countPlural=one"] = "c"
	if v1.Hash() == v2.Hash() {
		t.Error("a changed arm must change the hash")
	}
	if v1.Hash() == a.Hash() {
		t.Error("a variant and a string must not collide")
	}
}
